name: Hello World

on: push

jobs:
  hello-world-build:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Print Hello World!
        run: echo "Hello World!"

