services:
  renatsql:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: ${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:3306"
    networks:
      - mynet
    volumes:
      - data:/app/data
  
  myubuntu:
    image: ubuntu
    command: sleep 3600
    networks:
      - mynet

networks:
  mynet:

volumes:
  data:

