services:
  mynginx:
    image: nginx
    ports:
      - "8080:80"


  renatmysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD:1234
    volumes:
      - mydata:/var/lib/mysql

volumes:
  mydata: