services:
  rename_web:
    image: nginx
    ports:
      - "${MYPORT}:80"
    environment:
      NAME: ${NAME}
      AGE: ${AGE}
    volumes:
      - ${MYDATA}:/app/data
  
  renarmysql:
    image: mysql
    environment:
      MSL_ROOT_PASSWORD: 1234
