name: Hello World Workflow

on:
  push:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World!"

      - name: Show date
        run: echo "Current date is $(date)"

      - name: Show repository name
        run: echo "Repository is $GITHUB_REPOSITORY"
