name: My code#2
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Print ls command
        run: ls 
      - name: Print pwd command 
        run: pwd
      - name: Create file
        run: echo "hello from github actions" > file.txt
      - name: Looking the file content
        run: cat file.txt 
        
      