name: my second workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v4
        
      - name: Print Hello World!
        run: echo Hello World!

